# Generated by Django 2.1.7 on 2019-03-14 11:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('events', '0003_remove_events_user'),
        ('users', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='customuser',
            name='event',
            field=models.ManyToManyField(blank=True, to='events.Events'),
        ),
    ]
