# Generated by Django 2.2 on 2019-05-02 11:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='customuser',
            name='color_value',
            field=models.CharField(default='#d76565', max_length=7),
        ),
    ]
