# Generated by Django 2.1.7 on 2019-02-21 12:47

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('badges', '0002_badges_event'),
    ]

    operations = [
        migrations.AddField(
            model_name='badges',
            name='user',
            field=models.ManyToManyField(blank=True, to=settings.AUTH_USER_MODEL),
        ),
    ]
