INSERT INTO badgesdb.badges_users (id, name, e_mail, password) VALUES (1, 'Lars', 'test@test.test', 'password');
INSERT INTO badgesdb.badges_users (id, name, e_mail, password) VALUES (2, 'Espen', 'test@test.test', 'password');
INSERT INTO badgesdb.badges_users (id, name, e_mail, password) VALUES (3, 'Pål', 'test@test.test', 'password');
INSERT INTO badgesdb.badges_users (id, name, e_mail, password) VALUES (4, 'Per', 'test@test.test', 'password');
INSERT INTO badgesdb.badges_users (id, name, e_mail, password) VALUES (5, 'Knut', 'test@test.test', 'password');
INSERT INTO badgesdb.badges_users (id, name, e_mail, password) VALUES (6, 'Nils', 'test@test.test', 'password');
INSERT INTO badgesdb.badges_users (id, name, e_mail, password) VALUES (7, 'Marte', 'test@test.test', 'password');
INSERT INTO badgesdb.badges_users (id, name, e_mail, password) VALUES (8, 'Matilde', 'test@test.test', 'password');
INSERT INTO badgesdb.badges_users (id, name, e_mail, password) VALUES (9, 'Silje', 'test@test.test', 'password');
INSERT INTO badgesdb.badges_users (id, name, e_mail, password) VALUES (10, 'Hege', 'test@test.test', 'password');
INSERT INTO badgesdb.badges_users (id, name, e_mail, password) VALUES (11, 'Beate', 'test@test.test', 'password');
INSERT INTO badgesdb.badges_users (id, name, e_mail, password) VALUES (12, 'Jasper Knotten', 'test@test.test', 'password');
INSERT INTO badgesdb.badges_users (id, name, e_mail, password) VALUES (13, 'Jorunn Flo', 'test@test.test', 'password');
INSERT INTO badgesdb.badges_users (id, name, e_mail, password) VALUES (14, 'Sander', 'test@test.test', 'password');
INSERT INTO badgesdb.badges_users (id, name, e_mail, password) VALUES (15, 'Bashirmax', 'test@test.test', 'password');
INSERT INTO badgesdb.badges_users (id, name, e_mail, password) VALUES (16, 'Rannveig', 'test@test.test', 'password');